### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by tshemsedinov** [RV8V/Metadata-extractor#1]
Добавить eslint и конфигурацию, лучше взять эту: [.eslintrc.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json)

И права к репозиторию, чтоб можно было делать ревью.

**Comment by RV8V** [comment]
Я добавил Вас в колабораторы, открыл доступ

**Comment by tshemsedinov** [comment]
Линтер все еще нужен

**Comment by RV8V** [comment]
Добавил линтер, но describe, it, expect is not defined потому что они не обьявлены, но их же внедряет сам фреймворк jest, поэтому так и оставил
